### PR TITLE
Drag and drop support and some fixes

### PR DESCRIPTION
**Pull request by eysispeisi**
Supports the prebuilt tkdnd binaries you get with apt-get.

### CODE REVIEW

**Comment by heniotierra** [comment]
Right... there's one last thing, though. Can you and remove the two commits "fix for issue:" and "revert fix for issue:" ? For that, you can use the command 'git rebase'.

**Comment by heniotierra** [comment]
@eysispeisi On a second thought, ignore my previous comment. Just give me some time to test this.

**Comment by eysispeisi** [comment]
ok, thanks, been running in circles here. been learning a bit about git though

**Comment by heniotierra** [comment]
Thanks for all the work!

**Pull request merged**
