### PR TITLE
Progress bar and grip widget are now hidden by default and shown when…

### PR DESCRIPTION
**Pull request by eysispeisi**
… mouse moves over the player window. They are then hidden again 3 seconds after mouse stops moving over player window.

### CODE REVIEW

**Comment by eysispeisi** [comment]
change ae23079 also fixes a bug in the progress bar and grip widget hide/show change.

**Comment by heniotierra** [comment]
this gives me fatal error when I quit the video:

> 2017-01-22 19:57:32,163 - /opt/tboplayer/tboplayer.py - CRITICAL - fatal error, quitting and raising exception.
> Traceback (most recent call last):
>   File "/opt/tboplayer/tboplayer.py", line 2750, in <module>
>     bplayer = TBOPlayer()
>   File "/opt/tboplayer/tboplayer.py", line 1228, in __init__
>     self.root.mainloop()
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1124, in mainloop
>     self.tk.mainloop(n)
>   File "/opt/tboplayer/tboplayer.py", line 2681, in __call__
>     return apply(self.func, args)
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 586, in callit
>     func(*args)
>   File "/opt/tboplayer/tboplayer.py", line 1524, in vwindow_hide
>     self.vprogress_bar.lower(self.vprogress_bar_frame)
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 772, in lower
>     self.tk.call('lower', self._w, belowThis)
> _tkinter.TclError: bad window path name ".1939537632.1939534792"

**Comment by eysispeisi** [comment]
change ae23079 fixes the player throwing a fatal error, although the exception is still there, i will do a fix for that later today

**Comment by heniotierra** [comment]
yeah, it breaks tk loop

**Comment by eysispeisi** [comment]
change 90d9bd9 fixes the exception thrown

**Comment by heniotierra** [comment]
There's another problem: when in fullscfreen, it's possible to use the resizeing grip to change window size. This would be ok if when resizing the video from fullscreen would make the window behave as in windowed mode. But it does not allow moving the window, for example. If you'll allow using the resize grip in full screen mode, make the mode change to windowed.

**Comment by eysispeisi** [comment]
ah, yeah, i'll take care of that tomorrow, getting late here.

**Comment by heniotierra** [comment]
Also, instead of 4 commits, you can make only one... trying to keep commit history clean

**Comment by eysispeisi** [comment]
oops, i'll create another pull request shortly

**Pull request closed without merging**
